### ISSUE TITLE
à voir si utile module OCA - mail_activity ajout de partenaire

### ISSUE THREAD

**Issue by djulien19** [odoo-cae/odoo-addons-hr-incubator#19]
This module adds a partner and commercial partner field to activities

https://apps.odoo.com/apps/modules/12.0/mail_activity_partner/

**Comment by legalsylvain** [comment]
Hi @djulien19. Is it the good place to write that ? I think that we should restrict the issues to : 
- issues of the current modules
- Request for Comments, to improve modules 

don't you think ?
