### ISSUE TITLE
CI broken

### ISSUE THREAD

**Issue by legalsylvain** [odoo-cae/odoo-addons-hr-incubator#8]
Hi there ! 

Just FYI, CI is broken on master. The reason is simple. (at least one).

coopaname_custom depends on modules that are not available in the system. 
https://github.com/odoo-cae/odoo-addons-hr-incubator/blob/12.0/coopaname_custom/__manifest__.py#L10
@robinkeunen : could you fix it ? If you don't know how, please ping me. (it's about oca_dependencies.txt I guess).

In a general way, please avoid to merge PR if CI is red ! 

CC : @quentinDupont 

kind regards & happy new year !

**Comment by robinkeunen** [comment]
Hey Sylvain,

Yup I'll fix that, sorry. 

Happy new year down there.

@mclaeysb
